### ISSUE TITLE
Fails to build on 10.11.6

### ISSUE THREAD

**Issue by leonklingele** [jpouellet/signify-osx#8]
The project fails to build on 10.11.6:

```sh
$ make
clang -Isrc/include -Isrc/lib/libutil -include missing.h '-DDEF_WEAK(a)=asm("")' '-DMAKE_CLONE(a,b)=asm("")' '-Dpledge(a,b)=(0)' -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -Wno-unused-parameter -o signify src/lib/libc/crypt/blowfish.c src/lib/libc/hash/sha2.c src/lib/libc/net/base64.c src/lib/libc/string/explicit_bzero.c src/lib/libutil/bcrypt_pbkdf.c src/lib/libutil/ohash.c src/usr.bin/signify/crypto_api.c src/usr.bin/signify/fe25519.c src/usr.bin/signify/mod_ed25519.c src/usr.bin/signify/mod_ge25519.c src/usr.bin/signify/signify.c src/usr.bin/signify/sc25519.c src/usr.bin/signify/zsig.c src/lib/libc/hash/sha256hl.c src/lib/libc/hash/sha512hl.c src/lib/libc/hash/sha512_256hl.c hashaliases.c freezero.c
src/usr.bin/signify/signify.c:264:15: error: use of undeclared identifier 'RPP_STDIN'
                rppflags |= RPP_STDIN;
                            ^
src/usr.bin/signify/signify.c:269:30: error: use of undeclared identifier 'RPP_STDIN'
        if (confirm && !(rppflags & RPP_STDIN)) {
```

Is 10.11.6 still supported? Otherwise we'd need to increase the minimum support macOS version in the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/signify-osx.rb).

**Comment by barracuda156** [comment]
We need to fix the bug, not to prohibit building :) 

Indeed, it fails on all macOS versions now from 10.11 down. Unfortunately, `RPP_STDIN` is not present in `legacy-support`.

@catap Maybe you could suggest a fix for this?

**Comment by catap** [comment]
@barracuda156 `RPP_STDIN` says that read should be from stdin and not /dev/tty. 

So, you may "cover" it by `#ifdef`, otherwise you need to reimplement from scratch `readpassphrase()` and it isn't good idea.

**Comment by barracuda156** [comment]
> [@barracuda156](https://github.com/barracuda156) `RPP_STDIN` says that read should be from stdin and not /dev/tty.
> 
> So, you may "cover" it by `#ifdef`, otherwise you need to reimplement from scratch `readpassphrase()` and it isn't good idea.

@catap Turns out that there was a fallback code prior to https://github.com/jpouellet/signify-osx/commit/084e1de0e97c5a61b6c23eee3302d7a60a1861c3 so we simply need to restore that.

The only question is whether we rather use `legacy-support` for `getentropy` and `arc4random_buf` or restore fallbacks which were removed. What do you recommend?

**Comment by catap** [comment]
If legacy support has everything that you need it seems like the good approach for me
